#!/usr/bin/env bash

entries="Logout\nSuspend\nReboot\nShutdown"
selected=$(echo -e $entries|fuzzel --minimal-lines 0 --dmenu --cache /dev/null | awk '{print tolower($2)}')

case $selected in
  logout)
    hyprctl dispatch exit;;
  suspend)
    exec systemctl suspend;;
  reboot)
    exec systemctl reboot;;
  shutdown)
    exec systemctl poweroff;;
esac
